---

- name: "LOW | WN22-00-000180 | AUDIT | Windows Server 2022 non-administrative accounts or groups must only have print permissions on printer shares."
  block:
      - name: "LOW | WN22-00-000180 | AUDIT | Non-administrative accounts or groups must only have print permissions on printer shares. | Get Printer List"
        ansible.windows.win_shell: Get-Printer | where Shared -eq $true | fl Name, Type
        changed_when: false
        failed_when: false
        register: wn22_00_000180_audit

      - name: "LOW | WN22-00-000180 | AUDIT | Non-administrative accounts or groups must only have print permissions on printer shares. | Warning Message."
        ansible.builtin.debug:
            msg:
                - "Warning!! This is a manual task. Windows Server 2022 non-administrative accounts or groups"
                - "must only have print permissions on printer shares. If A Printer is showing shared please"
                - "configure the permissions on shared printers to restrict standard users to only have Print permissions."
                - "{{ wn22_00_000180_audit.stdout.split('\n') | trim }}"
        when: wn22_00_000180_audit.stdout | length > 0

      - name: "LOW | WN22-00-000180 | AUDIT | Non-administrative accounts or groups must only have print permissions on printer shares. | Warning Count"
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-00-000180'
        when: wn22_00_000180_audit.stdout | length > 0
  when:
      - wn22_00_000180
  tags:
      - WN22-00-000180
      - CAT3
      - CCI-000213
      - SRG-OS-000080-GPOS-00048
      - SV-254255r958472_rule
      - V-205664
      - NIST800-53_AC-3
      - NIST800-53_A_AC-3_1
      - NIST800-53_4_AC-3

- name: "LOW | WN22-00-000440 | AUDIT | The Windows Server 2022 time service must synchronize with an appropriate DoD time source."
  block:
      - name: "LOW | WN22-00-000440 | AUDIT | The Windows Server 2022 time service must synchronize with an appropriate DoD time source."
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. The Windows Server 2022 time service must synchronize with an appropriate DoD time source. "

      - name: "LOW | WN22-00-000440 | AUDIT |  The Windows Server 2022 time service must synchronize with an appropriate DoD time source. | import reusable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-00-000440'
  when: wn22_00_000440
  tags:
      - WN22-00-000440
      - CAT3
      - CCI-001891
      - SRG-OS-000355-GPOS-00143
      - SV-254281r1051090_rule
      - V-254281
      - NIST800-53_4_AU-8_1_a

- name: "LOW | WN22-CC-000030 | PATCH | Windows Server 2022 Internet Protocol version 6 (IPv6) source routing must be configured to the highest protection level to prevent IP source routing."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  when:
      - wn22_cc_000030
  tags:
      - WN22-CC-000030
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254335r991589_rule
      - V-205858
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_b

- name: "LOW | WN22-CC-000040 | PATCH | Windows Server 2022 source routing must be configured to the highest protection level to prevent Internet Protocol (IP) source routing."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  when:
      - wn22_cc_000040
  tags:
      - WN22-CC-000040
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254336r991589_rule	
      - V-205859
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_b

- name: "LOW | WN22-CC-000050 | PATCH | Windows Server 2022 must be configured to prevent Internet Control Message Protocol (ICMP) redirects from overriding Open Shortest Path First (OSPF)-generated routes."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: EnableICMPRedirect
      data: 0
      datatype: dword
  when:
      - wn22_cc_000050
  tags:
      - WN22-CC-000050
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254337r991589_rule
      - V-205860
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_b

- name: "LOW | WN22-CC-000060 | PATCH | Windows Server 2022 Must be configured to ignore NetBIOS name release requests except from WINS servers."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters
      value: NoNameReleaseOnDemand
      data: 1
      datatype: dword
  when:
      - wn22_cc_000060
  tags:
      - WN22-CC-000060
      - CAT3
      - CCI-002385
      - SRG-OS-000420-GPOS-00186
      - SV-254338r958902_rule
      - V-205822
      - NIST800-53_4_SC-5

- name: "LOW | WN22-CC-000200 | PATCH | Windows Server 2022 Application Compatibility Program Inventory must be prevented from collecting data and sending the information to Microsoft."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppCompat
      value: DisableInventory
      data: 1
      datatype: dword
  when:
      - wn22_cc_000200
  tags:
      - WN22-CC-000200
      - CAT3
      - CCI-000381
      - SRG-OS-000095-GPOS-00049
      - SV-254351r958478_rule
      - V-205691
      - NIST800-53_CM-7
      - NIST800-53_A_CM-7_1_ii
      - NIST800-53_4_CM-7_a

- name: "LOW | WN22-CC-000260 | PATCH | Windows Server 2022 Windows Update must not obtain updates from other PCs on the Internet."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization
      value: DODownloadMode
      data: 1
      datatype: dword
  when:
      - wn22_cc_000260
  tags:
      - WN22-CC-000260
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254357r991589_rule
      - V-205870
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_b

- name: "LOW | WN22-CC-000320 | AUDIT | Windows Server 2022 turning off File Explorer heap termination on corruption must be disabled."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer
      value: NoHeapTerminationOnCorruption
      state: present
      data: 0
      datatype: dword
  when:
      - wn22_cc_000320
  tags:
      - WN22-CC-000320
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254363r991589_rule
      - V-205871
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_b

- name: "LOW | WN22-DC-000160 | AUDIT | Windows Server 2022 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."
  block:
      - name: "LOW | WN22-DC-000160 | AUDIT | Windows Server 2022 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."
        ansible.builtin.debug:
            msg: "Warning!! This is a manual task. Windows Server 2022 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity."

      - name: "LOW | WN22-DC-000160 | AUDIT | Windows Server 2022 directory service must be configured to terminate LDAP-based network connections to the directory server after 5 minutes of inactivity. | import reusable task."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: 'WN22-DC-000160'
  when:
      - wn22_dc_000160
  tags:
      - WN22-DC-000160
      - CAT3
      - CCI-001133
      - SRG-OS-000163-GPOS-00072
      - SV-254400r970703_rule
      - V-205726
      - NIST800-53_SC-10
      - NIST800-53_A_SC-10_1_ii
      - NIST800-53_4_SC-10
      - NIST800-53_4_AC-12

- name: "LOW | WN22-SO-000140 | PATCH | Windows Server 2022 title for the legal banner must be configured with the appropriate text."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
      value: LegalNoticeCaption
      data: "{{ wn22stig_legalnoticecaption }}"
      datatype: string
  when:
      - wn22_so_000140
  tags:
      - WN22-SO-000140
      - CAT3
      - CCI-000048
      - CCI-001384
      - CCI-001385
      - CCI-001386
      - CCI-001387
      - CCI-001388
      - SRG-OS-000023-GPOS-00006
      - SRG-OS-000228-GPOS-00088
      - SV-254458r958390_rule
      - V-205632
      - NIST800-53-AC-8_a
      - NIST800-53_A_AC-8_1_ii
      - NIST800-53_4_AC-8_a
      - NIST800-53-AC-8_c
      - NIST800-53_A_AC-8_2_i
      - NIST800-53_4_AC-8_c_1
      - NIST800-53-AC-8_c
      - NIST800-53_A_AC-8_2_ii
      - NIST800-53_4_AC-8_c_2
      - NIST800-53-AC-8_c
      - NIST800-53_A_AC-8_2_iii
      - NIST800-53_4_AC-8_c_3

- name: "LOW | WN22-SO-000370 | PATCH | Windows Server 2022 default permissions of global system objects must be strengthened."
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
      value: ProtectionMode
      data: 1
      datatype: string
  when:
      - wn22_so_000370
  tags:
      - WN22-SO-000370
      - CAT3
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-254481r991589_rule
      - V-205871
      - NIST800-53_CM-6_b
      - NIST800-53_A_CM-6_1_iv
      - NIST800-53_4_CM-6_