---

- name: "LOW | WN22-SO-000140 | PATCH | Windows Server 2022 title for the legal banner must be configured with the appropriate text."
  when: wn22_so_000140 | bool
  tags:
    - WN22-SO-000140
    - CAT3
    - CCI-000048
    - CCI-001384
    - CCI-001385
    - CCI-001386
    - CCI-001387
    - CCI-001388
    - SRG-OS-000023-GPOS-00006
    - SRG-OS-000228-GPOS-00088
    - SV-254458r958390_rule
    - V-254458
    - NIST800-53_AC-8_a
    - NIST800-53_A_AC-8_1_ii
    - NIST800-53_4_AC-8_a
    - NIST800-53_AC-8_c
    - NIST800-53_A_AC-8_2_i
    - NIST800-53_4_AC-8_c_1
    - NIST800-53_A_AC-8_2_ii
    - NIST800-53_4_AC-8_c_2
    - NIST800-53_A_AC-8_2_iii
    - NIST800-53_4_AC-8_c_3
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    value: LegalNoticeCaption
    data: "{{ win22stig_legalnoticecaption }}"
    datatype: string

- name: "LOW | WN22-SO-000370 | PATCH | Windows Server 2022 default permissions of global system objects must be strengthened."
  when: wn22_so_000370 | bool
  tags:
    - WN22-SO-000370
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-254481r991589_rule
    - V-254481
    - NIST800-53_CM-6_b
    - NIST800-53_A_CM-6_1_iv
    - NIST800-53_4_CM-6_b
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
    value: ProtectionMode
    data: 1
    datatype: dword
